### ISSUE TITLE
horizontal melanopic calculation - adding Tau sky model and electric light 

### ISSUE THREAD

**Issue by nimafo** [taoning/pyrad_workshop_24#2]
Dear @taoning ,
Thank you for the nice tutorial, 

I need to add [ASHRAE Revised Clear Sky Model (“Tau Model”)](https://bigladdersoftware.com/epx/docs/8-4/engineering-reference/climate-calculations.html#ashrae-revised-clear-sky-model-tau-model) and electric lights (given .ies, spectral power distribution, light loss factor, spin angle, and tilt angle) as sources to the inputs for melanopic calculation. Can you please guide me on how that can be done?

Thank you,
Nima

**Comment by taoning** [comment]
Hello Nima,

It doesn't look like the "Tau" model is spectral, so you can just model it as regular Radiance sky.
For electric lights you can follow the instruction [here](https://www.radiance-online.org/community/workshops/2024-salt-lake-city-ut/presentations-1/W07_Spectral%20Simulation%20of%20Electrochromic%20Glass%20%20Using%20Python.pdf). 
You can use xform to move and rotate the electric lights.

**Comment by nimafo** [comment]
Thanks a lot for your response @taoning 👌🏼😊
